[theme]
base                     = "dark"
primaryColor             = "#FFC72C"
backgroundColor          = "#0D1321"
secondaryBackgroundColor = "#1D2436"
textColor                = "#F8FAFC"
font                     = "sans serif"

[server]
headless    = true
enableCORS  = false
